# Generated by Django 5.2.1 on 2025-06-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_typecontact_contactutilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('prestataire', 'Prestataire')], default='client', max_length=20),
        ),
    ]
