# Generated by Django 5.2.1 on 2025-06-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='nouvelle_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='nouvelle_heure',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='report_en_attente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptée', 'Acceptée'), ('refusée', 'Refusée'), ('terminée', 'Terminée'), ('annulée', 'Annulée'), ('reportée', 'Reportée')], default='en_attente', max_length=20),
        ),
    ]
