# Generated by Django 5.2.1 on 2025-06-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_reporteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptée', 'Acceptée'), ('refusée', 'Refusée'), ('terminée', 'Terminée'), ('annulée', 'Annulée'), ('en_attente_confirmation', 'En attente de confirmation'), ('reportée', 'Reportée')], default='en_attente', max_length=60),
        ),
    ]
