# Generated by Django 5.2.1 on 2025-06-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptée', 'Acceptée'), ('refusée', 'Refusée'), ('terminée', 'Terminée'), ('date_passée', 'Date passée'), ('annulée', 'Annulée'), ('en_attente_confirmation', 'En attente de confirmation'), ('reportée', 'Reportée')], default='en_attente', max_length=60),
        ),
    ]
