# Generated by Django 5.2.1 on 2025-06-13 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestataireBanni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=255)),
                ('date_bannissement', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('preuve', models.FileField(blank=True, null=True, upload_to='preuves_signalement/')),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
                ('defense', models.TextField(blank=True, null=True)),
                ('preuve_defense', models.FileField(blank=True, null=True, upload_to='preuves_defense/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('averti', 'Averti'), ('banni', 'Banni')], default='en_attente', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_faits', to=settings.AUTH_USER_MODEL)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='reservation.prestataire')),
            ],
        ),
    ]
