# Generated by Django 5.2.1 on 2025-06-13 16:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_newsletteremail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avis',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='prestataire',
            options={'ordering': ['utilisateur__name']},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date', '-heure']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='serviceoffert',
            options={'ordering': ['service__nom']},
        ),
        migrations.AlterModelOptions(
            name='signalement',
            options={'ordering': ['-date_signalement']},
        ),
        migrations.RemoveField(
            model_name='prestataire',
            name='tarifs',
        ),
        migrations.AlterField(
            model_name='avis',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_laisses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avis',
            name='note',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='avis',
            name='prestataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_recus', to='reservation.prestataire'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceoffert',
            name='prestataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='reservation.prestataire'),
        ),
    ]
